title: creatorbe links
subtitle: A way to convert something into a readable string
description: Hasan Basri aka creatorb [creatorbe], Linux enthusiasts who wrote about Programming and Islam.
author: creatorbe
github: https://github.com/creatorbe
about: Fullstack Programmer
disqus_shortname: creatorbe
google_analytics: UA-96556810-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  category:
    output: true
    permalink: /category/:path/

social:
    - icon: fa-whatsapp
      link: "https://wa.me/6289619060672"
    - icon: fa-envelope
      link: "mailto:creatorb45@gmail.com"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/creatorbe"
    - icon: fa-twitter
      link: "http://twitter.com/creatorbe"
    - icon: fa-github
      link: "https://github.com/creatorb"

share:
  twitter_username: creatorbe
  fb_appid: 1869209126686739

urls:
    - text: About
      url: /about/
    - text: Contact
      url: /contact/
    - text: Categories
      url: /category/android
    - text: Projects
      url: /projects/
    - text: CV
      # url: /cv.html
      url: https://drive.google.com/drive/folders/1oveQMGdYK6KNpTYmZ5OlkjvRroiQ9Qx4

url: "https://creatorbe.github.io"
baseurl: ""
paginate: 17
per_page: 17
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
